[project]
name = "second-brain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-community>=0.3.13",
    "markdown>=3.7",
    "pip>=24.3.1",
    "unstructured>=0.16.11",
]
